'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'RU' | 'EN';

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  RU: {
    'common.zodiac.aries': 'Овен',
    'common.zodiac.taurus': 'Телец',
    'common.zodiac.gemini': 'Близнецы',
    'common.zodiac.cancer': 'Рак',
    'common.zodiac.leo': 'Лев',
    'common.zodiac.virgo': 'Дева',
    'common.zodiac.libra': 'Весы',
    'common.zodiac.scorpio': 'Скорпион',
    'common.zodiac.sagittarius': 'Стрелец',
    'common.zodiac.capricorn': 'Козерог',
    'common.zodiac.aquarius': 'Водолей',
    'common.zodiac.pisces': 'Рыбы',
    // Landing / SEO
    'landing.headline': 'Найди свою идеальную пару сегодня',
    'landing.subheadline': 'SwiftMatch — умный способ познакомиться с интересными людьми рядом.',
    'landing.stats.users.num': '1M+',
    'landing.stats.users.label': 'Пользователей',
    'landing.stats.matches.num': '500K',
    'landing.stats.matches.label': 'Совпадений',
    'landing.stats.countries.num': '50+',
    'landing.stats.countries.label': 'Стран',
    
    // Bottom Nav
    'nav.home': 'Главная',
    'nav.search': 'Поиск',
    'nav.activity': 'Активность',
    'nav.chats': 'Чаты',
    'nav.profile': 'Профиль',
    'nav.groups': 'Группы',
    // Common Buttons
    'button.continue': 'Продолжить',
    'button.skip': 'Пропустить',
    'button.save': 'Сохранить',
    'button.back': 'Назад',
    'button.like': 'Лайк',
    'button.message': 'Сообщение',
    'button.send': 'Отправить',
    'button.search': 'Поиск',
    'button.filters': 'Фильтры',
    'button.autosearch': 'Автопоиск',
    'button.load_more': 'Показать еще',
    'button.start': 'Начать знакомства',
    'button.write_first': 'Написать первым',
    'button.close': 'Закрыть',
    'button.unlock': 'Разблокировать бесплатно',
    'button.watch': 'Смотреть',
    'button.not_now': 'Не сейчас',
    'button.report': 'Пожаловаться',
    'button.browse_profiles': 'Люди рядом',
    'button.join': 'Вступить',
    'button.leave_group': 'Выйти из группы',
    'button.vote': 'Голосовать',
    'button.participate': 'Участвовать',
    'button.reveal': 'Раскрыть',
    'button.cancel': 'Отмена',
    // Profile
    'profile.edit': 'Изменить',
    'profile.about': 'О себе',
    'profile.lifestyle': 'Данные',
    'profile.interests': 'Интересы',
    'profile.gallery': 'Галерея',
    'profile.gallery_reveal': 'Раскрыть',
    'profile.add': 'Добавить',
    'profile.likes': 'Лайков',
    'profile.matches': 'Мэтчей',
    'profile.age': 'Возраст',
    'profile.city': 'Москва',
    'profile.goal': 'Цель',
    'profile.goal_value': 'Серьезные отношения',
    'profile.height': 'Рост',
    'profile.pro': 'PRO 💎',
    'profile.someone': 'Кто-то',
    'profile.groups': 'Мои группы',
    'profile.rank': 'Звание',
    'profile.data_interests': 'Данные и Интересы',
    'profile.main_photo_label': 'Основное фото профиля',
    'profile.basic_info': 'Основные данные',
    'profile.profession': 'Профессия',
    'profile.education': 'Образование',
    'profile.zodiac_sign': 'Знак зодиака',
    'profile.custom_interest_placeholder': 'Свой вариант...',
    'profile.save_all': 'Сохранить все изменения',
    'profile.ai_improve': 'AI Улучшить',
    'profile.contest_selection_title': 'Выбор фото для конкурса',
    'profile.contest_selection_desc': 'Выберите лучшее фото из вашей галереи.',
    'profile.contest_submit': 'Подать заявку',
    'profile.application_sent': 'Заявка подана',
    // Lifestyle Labels
    'profile.label.zodiac': 'Зодиак',
    'profile.label.height': 'Рост',
    'profile.label.goal': 'Цель знакомства',
    'profile.label.education': 'Образование',
    'profile.label.job': 'Профессия',
    'profile.label.pets': 'Питомцы',
    'profile.label.sleep': 'Режим сна',
    'profile.label.gender': 'Мой пол',
    'profile.label.looking_for': 'Ищу',
    // Activity
    'activity.title': 'События',
    'activity.likes': 'Лайки',
    'activity.visits': 'Визиты',
    'activity.all': 'Все',
    'activity.new': 'новых',
    'activity.empty': 'Ничего не найдено',
    'activity.today_activity': 'Ваша активность сегодня',
    'activity.msg_like': 'поставила вам лайк',
    'activity.msg_visit': 'посетила ваш профиль',
    'activity.msg_match': 'новое совпадение с вами!',
    'activity.unlock_title': 'Бонус',
    'activity.unlock_desc': 'Посмотрите рекламу, чтобы открыть анкету бесплатно на 24 часа.',
    'activity.premium_title': 'Premium Доступ',
    'activity.premium_desc': 'Узнайте, кому вы понравились, и получите безлимитные лайки!',
    // Boost
    'boost.title': 'Поднять анкету',
    'boost.desc': 'Ваш профиль увидят в 10 раз больше людей в течение часа!',
    'boost.free': 'Бесплатно за рекламу',
    'boost.paid': 'Купить мгновенно',
    'boost.success_ad': 'Буст активирован за просмотр рекламы! 🔥',
    'boost.success_paid': 'Буст успешно куплен и активирован! 🔥',
    'autosearch.title': 'Доступ к Автопоиску',
    'autosearch.desc': 'Получите доступ к умному поиску, посмотрев рекламу или оплатив.',
    'autosearch.free': 'Бесплатно за рекламу',
    'autosearch.paid': 'Купить доступ',
    'autosearch.success_ad': 'Доступ к Автопоиску открыт!',
    'autosearch.success_paid': 'Доступ к Автопоиску куплен!',
    // Contest
    'contest.title': 'Фото Месяца',
    'contest.subtitle': 'Ежемесячный конкурс лучших фото',
    'contest.participate_banner': 'Твое фото может стать лучшим!',
    'contest.vote_banner': 'Голосуй за участников',
    'contest.leaderboard': 'Лидеры',
    'contest.all_participants': 'Все участники',
    'contest.ends_in': 'До конца осталось:',
    'contest.votes_count': 'голосов',
    'contest.submit_success': 'Ваше фото принято на конкурс! Удачи! 🍀',
    'contest.already_submitted': 'Вы уже участвуете в этом месяце.',
    'contest.select_photo': 'Выберите фото для конкурса',
    'contest.rules': 'Правила конкурса',
    'contest.rules_desc': 'Вы можете подать одну заявку в месяц. Победители получают статус PRO и бонусные суперлайки!',
    'contest.tab.women': 'Девушки',
    'contest.tab.men': 'Парни',
    'contest.prizes.title': 'Призы этого месяца',
    'contest.prizes.pro.title': 'Статус PRO',
    'contest.prizes.pro.desc': 'На 30 дней бесплатно',
    'contest.prizes.boost.title': '10 Бустов',
    'contest.prizes.boost.desc': 'Топ в ленте города',
    'contest.prizes.badge.title': 'Золотой бейдж',
    'contest.prizes.badge.desc': 'Уникальный знак отличия',
    'contest.quest.title': 'Ежедневное задание',
    'contest.quest.desc': 'Проголосуй за 5 участников, чтобы получить бонус',
    'contest.quest.reward': 'Награда: +1 Суперлайк',
    // Chats
    'chats.title': 'Сообщения',
    'chats.subtitle': 'Твои диалоги',
    'chats.search': 'Поиск по чатам и группам...',
    'chats.online': 'В сети',
    'chats.offline': 'Был(а) недавно',
    'chats.today': 'Сегодня',
    'chats.typing': 'печатает...',
    'chats.ai_themes': 'Темы ответов AI',
    'chats.close_themes': 'Закрыть темы',
    'chats.placeholder': 'Ваше сообщение...',
    'chats.members': 'участников',
    'cooldown.title': 'Сообщение не отправлено',
    'cooldown.description': 'Вы можете отправлять сообщения в группу раз в {seconds} секунд.',
    // Home / Search
    'home.popular': 'Популярное сейчас',
    'home.headline': 'Твой идеальный мэтч ждет тебя',
    'home.subheadline': 'Знакомься, общайся и находи любовь',
    'home.top_week': 'Топ недели',
    'home.recommend': 'Рекомендуем',
    'home.nearby': 'Люди рядом',
    'home.searching': 'Ищем лучших для вас...',
    'home.results': 'Результаты',
    'home.no_results': 'По вашим параметрам пока никого нет.',
    'match.title': 'Это совпадение!',
    'match.desc': 'Вы понравились друг другу. Не заставляйте ждать!',
    'match.insight': 'AI Инсайт',
    'swipes.nearby': 'анкет рядом',
    'match.insight_default': 'Вы отлично подходите друг другу!',
    'match.liked_each_other': 'понравились друг другу.',
    'user.match_score': 'Совпадение',
    'user.from_you': 'от вас',
    // Filter
    'filter.who_to_see': 'Кого вы ищете?',
    'filter.distance': 'Расстояние',
    'filter.goal': 'Цель знакомства',
    'filter.goal.all': 'Любая цель',
    'filter.gender.all': 'Все',
    'filter.gender.male': 'Мужчины',
    'filter.gender.female': 'Женщины',
    'filter.toast.title': 'Сообщение не отправлено',
    'filter.toast.description': 'Пожалуйста, избегайте ненормативной лексики, политических тем и ссылок.',
    'filter.toast.gibberish_description': 'Пожалуйста, пишите осмысленные сообщения. Бессмысленный набор букв запрещен.',
    // Onboarding
    'onboarding.step1.title': 'Как тебя зовут?',
    'onboarding.step1.desc': 'Имя будет отображаться в твоем профиле.',
    'onboarding.step1.label': 'Имя',
    'onboarding.step1.placeholder': 'Твое имя',
    'onboarding.step1.gender_label': 'Твой пол',
    'onboarding.step1.male': 'Мужчина',
    'onboarding.step1.female': 'Женщина',
    'onboarding.step2.title': 'Немного деталей',
    'onboarding.step2.desc': 'Это поможет нам найти людей поблизости.',
    'onboarding.step2.age': 'Возраст',
    'onboarding.step2.height': 'Рост (см)',
    'onboarding.step2.city': 'Город (опционально)',
    'onboarding.step2.city_placeholder': 'Где ты находишься?',
    'onboarding.step3.title': 'Личное',
    'onboarding.step3.desc': 'Расскажи о своих целях и знаке зодиака.',
    'onboarding.step3.goal_label': 'Цель знакомства',
    'onboarding.step3.goal_placeholder': 'Выберите цель',
    'onboarding.step3.zodiac_label': 'Знак зодиака',
    'onboarding.step3.zodiac_placeholder': 'Выберите знак',
    'onboarding.step4.title': 'Твои интересы',
    'onboarding.step4.desc': 'Выбери минимум 1, чтобы AI составил крутое био.',
    'onboarding.step5.title': 'Почти готово!',
    'onboarding.step5.desc': 'Добавь яркое фото и расскажи о себе или позволь AI помочь.',
    'onboarding.step5.photo_label': 'Выбрать фото',
    'onboarding.step5.bio_label': 'О себе',
    'onboarding.step5.bio_placeholder': 'Расскажи о своих увлечениях...',
    'onboarding.toast.photo_added': 'Фото добавлено!',
    'onboarding.toast.photo_desc': 'Ваш профиль теперь выглядит отлично.',
    'onboarding.toast.bio_ai': 'Био создано AI',
    'onboarding.toast.finish_title': 'Профиль готов!',
    'onboarding.toast.finish_desc': 'Добро пожаловать в SwiftMatch.',
    'onboarding.loc.detecting': 'Определяем местоположение...',
    'onboarding.loc.success': 'Город определен: ',
    'onboarding.loc.fail': 'Не удалось определить город',
    'onboarding.loc.denied': 'Доступ к геолокации отклонен',
    // Report
    'report.title': 'Жалоба на пользователя',
    'report.description': 'Ваша жалоба анонимна. Выберите причину, и мы рассмотрим ситуацию.',
    'report.reason.spam': 'Спам',
    'report.reason.abuse': 'Оскорбительное поведение',
    'report.reason.fake': 'Фейковый профиль',
    'report.reason.scam': 'Мошенничество',
    'report.reason.content': 'Неприемлемый контент',
    'report.details_placeholder': 'Дополнительные детали (необязательно)',
    'report.button.send': 'Отправить жалобу',
    'report.button.cancel': 'Отмена',
    'report.toast.success_title': 'Жалоба отправлена',
    'report.toast.success_desc': 'Спасибо! Мы рассмотрим вашу жалобу на',
    'report.toast.no_reason_title': 'Выберите причину',
    'report.toast.no_reason_desc': 'Необходимо указать причину для отправки жалобы.',
    // Settings
    'settings.account': 'Аккаунт',
    'settings.push_notifications': 'Push-уведомления',
    'settings.email_newsletter': 'Email-рассылка',
    'settings.location': 'Геолокация',
    'settings.discovery': 'Показывать меня',
    'settings.privacy': 'Приватность',
    'settings.incognito': 'Инкогнито',
    'settings.security': 'Безопасность',
    'settings.security.status': 'OK',
    'settings.support': 'Команда SwiftMatch',
    'settings.support.chat_title': 'Написать Команде',
    'settings.support.chat_desc': 'Чат с разработчиками приложения',
    'settings.about_app': 'О приложении',
    'settings.about_app_desc': 'Технологический стек и информация',
    'settings.legal': 'Юридическая информация',
    'settings.legal_desc': 'Политика, правила и согласия',
    'settings.privacy_policy': 'Политика конфиденциальности',
    'settings.terms_of_service': 'Пользовательское соглашение',
    'settings.data_consent': 'Согласие на обработку данных',
    'logout.title': 'Вы вышли из системы',
    'logout.button': 'Выйти',
    'delete_profile.button': 'Удалить профиль',
    // Support Chat
    'support.title': 'Команда SwiftMatch',
    'support.placeholder': 'Напишите ваше сообщение...',
    'support.greeting': 'Здравствуйте! Мы команда SwiftMatch. Чем можем помочь?',
    'support.response': 'Спасибо за ваше сообщение! Мы скоро свяжемся с вами.',
    'support.faq_promo': 'Не нашли ответ? Посетите наш',
    'support.faq_promo_link': 'раздел FAQ',
    // FAQ
    'faq.title': 'Вопросы и ответы',
    'faq.page_title': 'Часто задаваемые вопросы',
    'faq.description': 'Ответы на популярные вопросы',
    'faq.q1.question': 'Как я могу изменить свое фото профиля?',
    'faq.q1.answer': 'Вы можете изменить свои фотографии, перейдя в свой профиль, нажав на кнопку "Изменить" и затем на вашу главную фотографию или на свободные слоты в галерее.',
    'faq.q2.question': 'Безопасны ли мои платежные данные?',
    'faq.q2.answer': 'Да, абсолютно. Мы используем ведущие в отрасли платежные шлюзы, такие как Stripe, и не храним вашу платеную информацию на наших серверах.',
    'faq.q3.question': 'Что такое режим "Инкогнито"?',
    'faq.q3.answer': 'В режиме "Инкогнито" ваш профиль виден только тем, кому вы поставили лайк. Это дает вам больше контроля над вашей конфиденциальностью.',
    'faq.q4.question': 'Как я могу пожаловаться на пользователя?',
    'faq.q4.answer': 'Вы можете пожаловаться на пользователя прямо из его профиля или из окна чата, нажав на меню с тремя точками и выбрав "Пожаловаться".',
    'faq.q5.question': 'Как работает "Автопоиск"?',
    'faq.q5.answer': '"Автопоиск" использует ваши предпочтения (возраст, интересы) чтобы найти для вас наиболее подходящих людей. Вы можете настроить фильтры, чтобы уточнить поиск.',
    'faq.q6.question': 'Почему тормозит приложение?',
    'faq.q6.answer': 'Это может быть связано с: \n1. Нестабильной связью с интернетом или большой нагрузкой на сеть (3G, 4G).\n2. Большим количеством открытых приложений или вкладок в браузере (рекомендуем закрыть лишние).\n3. Работой лишних приложений в автозапуске или фоновом режиме.',
    'faq.q7.question': 'Что означают звания в моем профиле?',
    'faq.q7.answer': 'Звания — это система достижений SwiftMatch. Одно лучшее звание присваивается автоматически: \n1. Король свиданий — для самых популярных пользователей (мэтч 90%+).\n2. Душа компании — если у вас много интересов (5+).\n3. Обаяшка — если вы заполнили поле "О себе".\n4. Романтик — базовый статус для всех остальных.',
    'faq.q8.question': 'Почему мое сообщение не отправляется?',
    'faq.q8.answer': 'Для обеспечения безопасности и комфортного общения в приложении работает фильтр сообщений. Ваше сообщение может быть заблокировано, если оно содержит: \n- Нецензурную лексику \n- Спам или ссылки на сторонние ресурсы \n- Оскорбления или дискриминацию \n- Призывы к насилию \n- Обсуждение политических тем \n- Упоминание запрещенных товаров или мошеннических схем. \nПожалуйста, убедитесь, что ваше сообщение соответствует правилам сообщества.',
    'faq.q9.question': 'Как работает Фотоконкурс?',
    'faq.q9.answer': 'Фотоконкурс проходит ежемесячно. Вы можете выбрать одну фотографию из своего профиля для участия. Победители определяются по количеству голосов других пользователей и получают статус PRO, 10 бустов и уникальный золотой бейдж.',
    'faq.q10.question': 'Каковы основные правила использования приложения?',
    'faq.q10.answer': 'Мы стремимся создать безопасную среду. Запрещено использование нецензурной лексики, оскорблений, спама, размещение контента 18+ и политическая агитация. Нарушение правил может привести к временной или постоянной блокировке аккаунта.',
    // About App
    'about.title': 'О проекте SwiftMatch',
    'about.description': 'SwiftMatch — это современный полнофункциональный прототип приложения для знакомств (MVP), построенный на передовых веб-технологиях.',
    'about.stack.title': 'Технологический стек',
    'about.frontend.title': 'Фронтенд',
    'about.frontend.desc': 'Next.js 15, React 19, TypeScript, Tailwind CSS, ShadCN UI.',
    'about.backend.title': 'Бэкенд & База данных',
    'about.backend.desc': 'Firebase (Auth, Firestore) — обеспечивает работу в реальном времени и надежное хранение данных.',
    'about.ai.title': 'Искусственный интеллект',
    'about.ai.desc': 'Genkit (Google AI) — используется для анализа совместимости, генерации био и фраз для начала разговора.',
    'about.performance.title': 'Производительность',
    'about.performance.desc': 'Серверные компоненты (RSC), оптимизация изображений и бандла для мгновенной загрузки на мобильных.',
    // Admin
    'admin.dashboard': 'Дашборд',
    'admin.users': 'Пользователи',
    'admin.reports': 'Жалобы',
    'admin.features': 'Функции',
    'admin.back_to_app': 'В приложение',
    'admin.logout': 'Выход',
    'admin.total_users': 'Всего пользователей',
    'admin.online_users': 'В сети',
    'admin.new_users': 'Новые сегодня',
    'admin.total_matches': 'Всего мэтчей',
    'admin.manage_users': 'Все пользователи',
    'admin.manage_features': 'Управление функциями',
    'admin.manage_reports': 'Управление жалобами',
    'admin.feature_desc': 'Включайте функции в реальном времени.',
    'admin.save': 'Сохранить',
    'admin.reset': 'Сбросить',
    'admin.status': 'Статус',
    'admin.joined': 'Регистрация',
    'admin.actions': 'Действия',
    'admin.city': 'Город',
    'admin.user_image': 'Фото',
    'admin.user_name': 'Имя',
    'admin.reporter': 'Пожаловался',
    'admin.reported_user': 'Пользователь',
    'admin.reason': 'Причина',
    'admin.date': 'Дата',
    'admin.report_new': 'Новая',
    'admin.report_resolved': 'Решена',
    'admin.view_profile': 'Просмотреть профиль',
    'admin.mark_resolved': 'Отметить как решенный',
    'admin.block_user': 'Заблокировать',
    'admin.delete_user': 'Удалить пользователя',
    'admin.no_reports': 'Жалоб пока нет',
    'admin.monetization.title': 'Монетизация',
    'admin.monetization.description': 'Настройте рекламные сети для вознаграждений.',
    'admin.monetization.google_desc': 'Показывать рекламу из Google AdMob.',
    'admin.monetization.yandex_desc': 'Показывать рекламу из Рекламной сети Яндекса.',
    'admin.monetization.ad_unit_id': 'ID рекламного блока',
    'admin.monetization.save_success_title': 'Настройки монетизации сохранены',
    'admin.monetization.save_success_desc': 'Изменения будут применены в приложении.',
    'admin.content.title': 'Контент',
    'admin.content.description': 'Управляйте списками, используемыми в приложении.',
    'admin.content.interests.title': 'Интересы',
    'admin.content.dating_goals.title': 'Цели знакомства',
    'admin.content.education.title': 'Образование',
    'admin.content.interests.save_toast': 'Список интересов обновлен',
    'admin.content.goals.save_toast': 'Список целей обновлен',
    'admin.content.education.save_toast': 'Список образования обновлен',
    'admin.messaging.title': 'Рассылка',
    'admin.messaging.description': 'Отправляйте сообщения всем пользователям приложения или по Email.',
    'admin.messaging.subject': 'Тема сообщения',
    'admin.messaging.message': 'Текст сообщения',
    'admin.messaging.send': 'Отправить рассылку',
    'admin.messaging.send_success_title': 'Рассылка отправлена',
    'admin.messaging.send_success_desc': 'Ваше сообщение скоро будет доставлено пользователям.',
    'admin.messaging.type.app': 'В приложении',
    'admin.messaging.type.email': 'Email рассылка',
    'admin.messaging.recipients': 'Получатели',
    'admin.messaging.recipients.all': 'Все пользователи',
    'admin.messaging.recipients.premium': 'Только Premium',
    'admin.messaging.recipients.new': 'Новые (за 24ч)',
    'admin.docs.title': 'Документация',
    'admin.docs.desc': 'Техническое описание, функционал и логика работы приложения.',
    'admin.docs.about_title': 'О проекте и стеке',
    'admin.docs.features_title': 'Реализованный функционал',
    'admin.docs.logic_title': 'Логика Автопоиска',
    'dialog.delete_photo.title': 'Удалить фото?',
    'dialog.delete_photo.description': 'Это действие необратимо. Вы уверены, что хотите удалить эту фотографию?',
    'dialog.delete_photo.confirm': 'Удалить',
    'dialog.delete_photo.cancel': 'Отмена',
    'delete_photo_error.title': 'Нельзя удалить',
    'delete_photo_error.description': 'Вы не можете удалить последнее фото в галерее.',
    'settings.incognito.enabled_desc': 'Ваши визиты теперь скрыты.',
    'settings.incognito.disabled_desc': 'Ваши визиты снова видны.',
    'incognito.banner.title': 'Режим Инкогнито',
    'incognito.banner.description': 'Ваши посещения профилей других пользователей не будут отображаться в их активности.',
    'incognito.toast.title': 'Режим Инкогнито',
    'incognito.toast.description': 'Ваш визит на эту страницу останется анонимным.',
    'toast.left_group': 'Вы вышли из группы',
    'groups.ad.title': 'Разблокировать премиум группу!',
    'groups.ad.description': 'Посмотрите короткую рекламу и получите доступ.',
    'groups.ad.toast.title': 'Демонстрация рекламы',
    'groups.ad.toast.description': 'Здесь мог бы быть просмотр видео для получения бонуса!',
    // PWA Install
    'pwa.install.title': 'Установить приложение?',
    'pwa.install.description': 'Добавьте SwiftMatch на главный экран для быстрого доступа и лучшего опыта.',
    'pwa.install.button': 'Установить',
    'pwa.install.cancel': 'Позже',
    'pwa.install.success': 'Приложение успешно установлено!',
    'pwa.install.dismissed': 'Вы можете установить приложение позже из меню браузера.',
    'pwa.install.ios_title': 'Установка на iOS',
    'pwa.install.ios_description': 'Чтобы установить SwiftMatch на ваш iPhone, нажмите кнопку «Поделиться» и выберите «На экран "Домой"».',

    // Groups
    'groups.tabs.find': 'Популярные',
    'groups.tabs.top': 'Топ недели',
    'groups.tabs.my': 'Мои группы',
    'groups.create_button': 'Создать группу',
    'groups.not_found': 'Группы не найдены.',
    'groups.no_top_groups': 'На этой неделе нет популярных групп.',
    'groups.not_joined': 'Вы не состоите в группах.',
    'groups.create.title': 'Создать новую группу',
    'groups.create.description': 'Заполните информацию, чтобы создать новое сообщество для общения по интересам.',
    'groups.create.name_label': 'Название группы',
    'groups.create.name_placeholder': 'Например: Клуб любителей книг',
    'groups.create.desc_label': 'Описание',
    'groups.create.desc_placeholder': 'Расскажите, чему посвящена ваша группа и какие у вас цели.',
    'groups.create.category_label': 'Тема',
    'groups.create.category_placeholder': 'Выберите основную тему группы',
    'groups.create.submit': 'Создать группу',
    'groups.create.error_title': 'Ошибка',
    'groups.create.error_desc': 'Название группы и категория обязательны.',
    'groups.create.forbidden_title': 'Недопустимые слова',
    'groups.create.forbidden_desc': 'Название или описание содержит недопустимые слова.',
    'groups.create.success_title': 'Группа создана!',
    'groups.create.success_desc_start': 'Ваша группа "',
    'groups.create.success_desc_end': '" была успешно создана.',
  },
  EN: {
    'common.zodiac.aries': 'Aries',
    'common.zodiac.taurus': 'Taurus',
    'common.zodiac.gemini': 'Gemini',
    'common.zodiac.cancer': 'Cancer',
    'common.zodiac.leo': 'Leo',
    'common.zodiac.virgo': 'Virgo',
    'common.zodiac.libra': 'Libra',
    'common.zodiac.scorpio': 'Scorpio',
    'common.zodiac.sagittarius': 'Sagittarius',
    'common.zodiac.capricorn': 'Capricorn',
    'common.zodiac.aquarius': 'Aquarius',
    'common.zodiac.pisces': 'Pisces',
    // Landing / SEO
    'landing.headline': 'Find your perfect match today',
    'landing.subheadline': 'SwiftMatch — a smart way to meet interesting people nearby.',
    'landing.stats.users.num': '1M+',
    'landing.stats.users.label': 'Users',
    'landing.stats.matches.num': '500K',
    'landing.stats.matches.label': 'Matches',
    'landing.stats.countries.num': '50+',
    'landing.stats.countries.label': 'Countries',

    // Bottom Nav
    'nav.home': 'Home',
    'nav.search': 'Search',
    'nav.activity': 'Activity',
    'nav.chats': 'Chats',
    'nav.profile': 'Profile',
    'nav.groups': 'Groups',
    // Common Buttons
    'button.continue': 'Continue',
    'button.skip': 'Skip',
    'button.save': 'Save',
    'button.back': 'Back',
    'button.like': 'Like',
    'button.message': 'Message',
    'button.send': 'Send',
    'button.search': 'Search',
    'button.filters': 'Filters',
    'button.autosearch': 'Auto-search',
    'button.load_more': 'Load more',
    'button.start': 'Start dating',
    'button.write_first': 'Write first',
    'button.close': 'Close',
    'button.unlock': 'Unlock for free',
    'button.watch': 'Watch',
    'button.not_now': 'Not now',
    'button.report': 'Report',
    'button.browse_profiles': 'Browse Profiles',
    'button.join': 'Join',
    'button.leave_group': 'Leave Group',
    'button.vote': 'Vote',
    'button.participate': 'Participate',
    'button.reveal': 'Reveal',
    'button.cancel': 'Cancel',
    // Profile
    'profile.edit': 'Edit',
    'profile.about': 'About Me',
    'profile.lifestyle': 'Details',
    'profile.interests': 'Interests',
    'profile.gallery': 'Gallery',
    'profile.gallery_reveal': 'Reveal',
    'profile.add': 'Add',
    'profile.likes': 'Likes',
    'profile.matches': 'Matches',
    'profile.age': 'Age',
    'profile.city': 'Moscow',
    'profile.goal': 'Goal',
    'profile.goal_value': 'Serious relationship',
    'profile.height': 'Height',
    'profile.pro': 'PRO 💎',
    'profile.someone': 'Someone',
    'profile.groups': 'My Groups',
    'profile.rank': 'Title',
    'profile.data_interests': 'Info & Interests',
    'profile.main_photo_label': 'Main profile photo',
    'profile.basic_info': 'Basic Info',
    'profile.profession': 'Occupation',
    'profile.education': 'Education',
    'profile.zodiac_sign': 'Zodiac Sign',
    'profile.custom_interest_placeholder': 'Custom option...',
    'profile.save_all': 'Save all changes',
    'profile.ai_improve': 'AI Improve',
    'profile.contest_selection_title': 'Choose photo for contest',
    'profile.contest_selection_desc': 'Select the best photo from your gallery.',
    'profile.contest_submit': 'Submit Entry',
    'profile.application_sent': 'Application Sent',
    // Lifestyle Labels
    'profile.label.zodiac': 'Zodiac',
    'profile.label.height': 'Height',
    'profile.label.goal': 'Dating Goal',
    'profile.label.education': 'Education',
    'profile.label.job': 'Occupation',
    'profile.label.pets': 'Pets',
    'profile.label.sleep': 'Sleep',
    'profile.label.gender': 'My Gender',
    'profile.label.looking_for': 'Looking for',
    // Activity
    'activity.title': 'Activity',
    'activity.likes': 'Likes',
    'activity.visits': 'Visits',
    'activity.all': 'All',
    'activity.new': 'new',
    'activity.empty': 'Nothing found',
    'activity.today_activity': 'Your activity today',
    'activity.msg_like': 'liked you',
    'activity.msg_visit': 'visited your profile',
    'activity.msg_match': 'new match with you!',
    'activity.unlock_title': 'Bonus',
    'activity.unlock_desc': 'Watch an ad to unlock the profile for free for 24 hours.',
    'activity.premium_title': 'Premium Access',
    'activity.premium_desc': 'Find out who liked you and get unlimited likes!',
    // Boost
    'boost.title': 'Boost Profile',
    'boost.desc': 'Your profile will be seen by 10x more people for one hour!',
    'boost.free': 'Free with Ad',
    'boost.paid': 'Buy Instant Boost',
    'boost.success_ad': 'Boost activated via ad! 🔥',
    'boost.success_paid': 'Boost purchased and activated! 🔥',
    'autosearch.title': 'Autosearch Access',
    'autosearch.desc': 'Get access to smart search by watching an ad or paying.',
    'autosearch.free': 'Free with Ad',
    'autosearch.paid': 'Buy Access',
    'autosearch.success_ad': 'Autosearch access unlocked!',
    'autosearch.success_paid': 'Autosearch access purchased!',
    // Contest
    'contest.title': 'Photo of the Month',
    'contest.subtitle': 'Monthly best photo contest',
    'contest.participate_banner': 'Your photo can be the best!',
    'contest.vote_banner': 'Vote for participants',
    'contest.leaderboard': 'Leaders',
    'contest.all_participants': 'All participants',
    'contest.ends_in': 'Ends in:',
    'contest.votes_count': 'votes',
    'contest.submit_success': 'Your photo has been accepted! Good luck! 🍀',
    'contest.already_submitted': 'You are already participating this month.',
    'contest.select_photo': 'Select photo for the contest',
    'contest.rules': 'Contest Rules',
    'contest.rules_desc': 'You can submit one entry per month. Winners get PRO status and bonus superlikes!',
    'contest.tab.women': 'Women',
    'contest.tab.men': 'Men',
    'contest.prizes.title': 'This Month\'s Prizes',
    'contest.prizes.pro.title': 'PRO Status',
    'contest.prizes.pro.desc': 'For 30 days free',
    'contest.prizes.boost.title': '10 Boosts',
    'contest.prizes.boost.desc': 'Top in city feed',
    'contest.prizes.badge.title': 'Golden Badge',
    'contest.prizes.badge.desc': 'Unique distinction mark',
    'contest.quest.title': 'Daily Quest',
    'contest.quest.desc': 'Vote for 5 participants to get a bonus',
    'contest.quest.reward': 'Reward: +1 Superlike',
    // Chats
    'chats.title': 'Messages',
    'chats.subtitle': 'Your dialogs',
    'chats.search': 'Search chats and groups...',
    'chats.online': 'Online',
    'chats.offline': 'Was recently',
    'chats.today': 'Today',
    'chats.typing': 'typing...',
    'chats.ai_themes': 'AI Reply Themes',
    'chats.close_themes': 'Close themes',
    'chats.placeholder': 'Your message...',
    'chats.members': 'members',
    'cooldown.title': 'Message not sent',
    'cooldown.description': 'You can send messages to the group once every {seconds} seconds.',
    // Home / Search
    'home.popular': 'Popular now',
    'home.headline': 'Your ideal match is waiting',
    'home.subheadline': 'Meet, chat and find love',
    'home.top_week': 'Top of the week',
    'home.recommend': 'Recommended',
    'home.nearby': 'Nearby',
    'home.searching': 'Searching for the best...',
    'home.results': 'Results',
    'home.no_results': 'No one found with these parameters.',
    'match.title': 'It\'s a Match!',
    'match.desc': 'You liked each other. Don\'t keep them waiting!',
    'match.insight': 'AI Insight',
    'swipes.nearby': 'profiles nearby',
    'match.insight_default': 'You are a great match!',
    'match.liked_each_other': 'liked each other.',
    'user.match_score': 'Match',
    'user.from_you': 'from you',
    // Filter
    'filter.who_to_see': 'Who are you looking for?',
    'filter.distance': 'Distance',
    'filter.goal': 'Dating Goal',
    'filter.goal.all': 'Any goal',
    'filter.gender.all': 'All',
    'filter.gender.male': 'Men',
    'filter.gender.female': 'Women',
    'filter.toast.title': 'Message Not Sent',
    'filter.toast.description': 'Please avoid profanity, political topics, and links.',
    'filter.toast.gibberish_description': 'Please write meaningful messages. Gibberish is not allowed.',
    // Onboarding
    'onboarding.step1.title': "What's your name?",
    'onboarding.step1.desc': 'Name will be displayed in your profile.',
    'onboarding.step1.label': 'Name',
    'onboarding.step1.placeholder': 'Your name',
    'onboarding.step1.gender_label': 'Your gender',
    'onboarding.step1.male': 'Male',
    'onboarding.step1.female': 'Female',
    'onboarding.step2.title': 'A few details',
    'onboarding.step2.desc': 'This helps us find people nearby.',
    'onboarding.step2.age': 'Age',
    'onboarding.step2.height': 'Height (cm)',
    'onboarding.step2.city': 'City (optional)',
    'onboarding.step2.city_placeholder': 'Where are you located?',
    'onboarding.step3.title': 'Personal',
    'onboarding.step3.desc': 'Tell us about your goals and zodiac sign.',
    'onboarding.step3.goal_label': 'Dating goal',
    'onboarding.step3.goal_placeholder': 'Select goal',
    'onboarding.step3.zodiac_label': 'Zodiac sign',
    'onboarding.step3.zodiac_placeholder': 'Select sign',
    'onboarding.step4.title': 'Your interests',
    'onboarding.step4.desc': 'Select at least 1 so AI can draft a cool bio.',
    'onboarding.step5.title': 'Almost ready!',
    'onboarding.step5.desc': 'Add a bright photo and tell us about yourself or let AI help.',
    'onboarding.step5.photo_label': 'Select photo',
    'onboarding.step5.bio_label': 'About me',
    'onboarding.step5.bio_placeholder': 'Tell us about your hobbies...',
    'onboarding.toast.photo_added': 'Photo added!',
    'onboarding.toast.photo_desc': 'Your profile looks great now.',
    'onboarding.toast.bio_ai': 'Bio created by AI',
    'onboarding.toast.finish_title': 'Profile is ready!',
    'onboarding.toast.finish_desc': 'Welcome to SwiftMatch.',
    'onboarding.loc.detecting': 'Determining location...',
    'onboarding.loc.success': 'City determined: ',
    'onboarding.loc.fail': 'Could not determine city accurately',
    'onboarding.loc.denied': 'Geolocation access denied',
    // Report
    'report.title': 'Report User',
    'report.description': 'Your report is anonymous. Please select a reason, and we will review the situation.',
    'report.reason.spam': 'Spam',
    'report.reason.abuse': 'Abusive behavior',
    'report.reason.fake': 'Fake profile',
    'report.reason.scam': 'Scam',
    'report.reason.content': 'Inappropriate content',
    'report.details_placeholder': 'Additional details (optional)',
    'report.button.send': 'Send Report',
    'report.button.cancel': 'Cancel',
    'report.toast.success_title': 'Report sent',
    'report.toast.success_desc': 'Thank you! We will review your report on',
    'report.toast.no_reason_title': 'Select a reason',
    'report.toast.no_reason_desc': 'A reason is required to send a report.',
    // Settings
    'settings.account': 'Account',
    'settings.push_notifications': 'Push Notifications',
    'settings.email_newsletter': 'Email Newsletter',
    'settings.location': 'Geolocation',
    'settings.discovery': 'Show me',
    'settings.privacy': 'Privacy',
    'settings.incognito': 'Incognito',
    'settings.security': 'Security',
    'settings.security.status': 'OK',
    'settings.support': 'SwiftMatch Team',
    'settings.support.chat_title': 'Message the Team',
    'settings.support.chat_desc': 'Chat with app developers',
    'settings.about_app': 'About the App',
    'settings.about_app_desc': 'Tech stack and info',
    'settings.legal': 'Legal Information',
    'settings.legal_desc': 'Policies, rules and consents',
    'settings.privacy_policy': 'Privacy Policy',
    'settings.terms_of_service': 'Terms of Service',
    'settings.data_consent': 'Data Processing Consent',
    'logout.title': 'You have been logged out',
    'logout.button': 'Logout',
    'delete_profile.button': 'Delete Profile',
    // Support Chat
    'support.title': 'SwiftMatch Team',
    'support.placeholder': 'Write your message...',
    'support.greeting': 'Hello! We are the SwiftMatch Team. How can we help?',
    'support.response': 'Thank you for your message! We will contact you soon.',
    'support.faq_promo': 'Can\'t find an answer? Visit our',
    'support.faq_promo_link': 'FAQ section',
    // FAQ
    'faq.title': 'FAQ',
    'faq.page_title': 'Frequently Asked Questions',
    'faq.description': 'Answers to popular questions',
    'faq.q1.question': 'How can I change my profile picture?',
    'faq.q1.answer': 'You can change your photos by going to your profile, clicking the "Edit" button, and then tapping on your main photo or empty gallery slots.',
    'faq.q2.question': 'Is my payment information secure?',
    'faq.q2.answer': 'Yes, absolutely. We use industry-leading payment gateways like Stripe and do not store your payment information on our servers.',
    'faq.q3.question': 'What is "Incognito" mode?',
    'faq.q3.answer': 'In "Incognito" mode, your profile is only visible to people you have liked. This gives you more control over your privacy.',
    'faq.q4.question': 'How can I report a user?',
    'faq.q4.answer': 'You can report a user directly from their profile or from the chat window by clicking on the three-dots menu and selecting "Report".',
    'faq.q5.question': 'How does "Auto-search" work?',
    'faq.q5.answer': '"Auto-search" uses your preferences (age, interests) to find the most suitable people for you. You can adjust the filters to refine your search.',
    'faq.q6.question': 'Why is the app slow?',
    'faq.q6.answer': 'This could be due to: \n1. Unstable internet connection or high network load (3G, 4G).\n2. Many open apps or browser tabs (we recommend closing unused ones).\n3. Unnecessary background apps or startup items running on your device.',
    'faq.q7.question': 'What do the titles in my profile mean?',
    'faq.q7.answer': 'Titles are SwiftMatch\'s achievement system. One best title is assigned automatically: \n1. Dating King — for the most popular users (90%+ match).\n2. Life of the Party — if you have many interests (5+).\n3. Charming — if you filled out your bio.\n4. Romantic — the base status for everyone else.',
    'faq.q8.question': 'Why is my message not being sent?',
    'faq.q8.answer': 'To ensure a safe and comfortable environment, the application has a message filter. Your message may be blocked if it contains: \n- Profanity \n- Spam or links to external resources \n- Insults or discrimination \n- Calls to violence \n- Discussion of political topics \n- Mention of prohibited goods or fraudulent schemes. \nPlease ensure your message complies with the community guidelines.',
    'faq.q9.question': 'How does the Photo Contest work?',
    'faq.q9.answer': 'The Photo Contest takes place monthly. You can select one photo from your profile to participate. Winners are determined by the number of votes from other users and receive PRO status, 10 boosts, and a unique golden badge.',
    'faq.q10.question': 'What are the main rules for using the app?',
    'faq.q10.answer': 'We aim to create a safe environment. Profanity, insults, spam, 18+ content, and political campaigning are prohibited. Violation of these rules may lead to temporary or permanent account suspension.',
    // About App
    'about.title': 'About SwiftMatch Project',
    'about.description': 'SwiftMatch is a modern, full-featured dating app prototype (MVP) built with cutting-edge web technologies.',
    'about.stack.title': 'Technical Stack',
    'about.frontend.title': 'Frontend',
    'about.frontend.desc': 'Next.js 15, React 19, TypeScript, Tailwind CSS, ShadCN UI.',
    'about.backend.title': 'Backend & Database',
    'about.backend.desc': 'Firebase (Auth, Firestore) — provides real-time updates and secure data storage.',
    'about.ai.title': 'Artificial Intelligence',
    'about.ai.desc': 'Genkit (Google AI) — used for compatibility analysis, bio generation, and icebreaker suggestions.',
    'about.performance.title': 'Performance',
    'about.performance.desc': 'Server Components (RSC), image optimization, and bundle optimization for instant loading on mobile.',
    // Admin
    'admin.dashboard': 'Dashboard',
    'admin.users': 'Users',
    'admin.reports': 'Reports',
    'admin.features': 'Features',
    'admin.back_to_app': 'Back to App',
    'admin.logout': 'Logout',
    'admin.total_users': 'Total Users',
    'admin.online_users': 'Online Users',
    'admin.new_users': 'New Today',
    'admin.total_matches': 'Total Matches',
    'admin.manage_users': 'Manage Users',
    'admin.manage_features': 'Manage Features',
    'admin.manage_reports': 'Manage Reports',
    'admin.feature_desc': 'Enable or disable features in real-time.',
    'admin.save': 'Save Changes',
    'admin.reset': 'Reset',
    'admin.status': 'Status',
    'admin.joined': 'Joined',
    'admin.actions': 'Actions',
    'admin.city': 'City',
    'admin.user_image': 'Image',
    'admin.user_name': 'Name',
    'admin.reporter': 'Reporter',
    'admin.reported_user': 'User',
    'admin.reason': 'Reason',
    'admin.date': 'Date',
    'admin.report_new': 'New',
    'admin.report_resolved': 'Resolved',
    'admin.view_profile': 'View Profile',
    'admin.mark_resolved': 'Mark as Resolved',
    'admin.block_user': 'Block',
    'admin.delete_user': 'Delete User',
    'admin.no_reports': 'No reports yet',
    'admin.monetization.title': 'Monetization',
    'admin.monetization.description': 'Configure ad networks for rewards.',
    'admin.monetization.google_desc': 'Show ads from Google AdMob.',
    'admin.monetization.yandex_desc': 'Show ads from Yandex Advertising Network.',
    'admin.monetization.ad_unit_id': 'Ad Unit ID',
    'admin.monetization.save_success_title': 'Monetization settings saved',
    'admin.monetization.save_success_desc': 'Changes will be applied in the app.',
    'admin.content.title': 'Content',
    'admin.content.description': 'Manage lists used in the application, such as interests and dating goals.',
    'admin.content.interests.title': 'Interests',
    'admin.content.dating_goals.title': 'Dating Goals',
    'admin.content.education.title': 'Education',
    'admin.content.interests.save_toast': 'Interests list updated',
    'admin.content.goals.save_toast': 'Goals list updated',
    'admin.content.education.save_toast': 'Education list updated',
    'admin.messaging.title': 'Newsletter',
    'admin.messaging.description': 'Send messages to all application users or via Email.',
    'admin.messaging.subject': 'Message Subject',
    'admin.messaging.message': 'Message Body',
    'admin.messaging.send': 'Send Newsletter',
    'admin.messaging.send_success_title': 'Newsletter Sent',
    'admin.messaging.send_success_desc': 'Your message will be delivered to users shortly.',
    'admin.messaging.type.app': 'In-App',
    'admin.messaging.type.email': 'Email Campaign',
    'admin.messaging.recipients': 'Recipients',
    'admin.messaging.recipients.all': 'All users',
    'admin.messaging.recipients.premium': 'Premium only',
    'admin.messaging.recipients.new': 'New (24h)',
    'admin.docs.title': 'Documentation',
    'admin.docs.desc': 'Technical description, features and application logic.',
    'admin.docs.about_title': 'About Project & Stack',
    'admin.docs.features_title': 'Implemented Features',
    'admin.docs.logic_title': 'Autosearch Logic',
    'dialog.delete_photo.title': 'Delete Photo?',
    'dialog.delete_photo.description': 'This action cannot be undone. Are you sure you want to delete this photo?',
    'dialog.delete_photo.confirm': 'Delete',
    'dialog.delete_photo.cancel': 'Cancel',
    'delete_photo_error.title': 'Cannot Delete',
    'delete_photo_error.description': 'You cannot delete the last photo in your gallery.',
    'settings.incognito.enabled_desc': 'Your visits are now hidden.',
    'settings.incognito.disabled_desc': 'Your visits are visible again.',
    'incognito.banner.title': 'Incognito Mode',
    'incognito.banner.description': 'Your visits to other profiles will not be shown in their activity.',
    'incognito.toast.title': 'Incognito Mode',
    'incognito.toast.description': 'Your visit to this page will remain anonymous.',
    'toast.left_group': 'You have left the group',
    'groups.ad.title': 'Unlock a Premium Group!',
    'groups.ad.description': 'Watch a short ad to get access.',
    'groups.ad.toast.title': 'Ad Demonstration',
    'groups.ad.toast.description': 'A video could be playing here to get a bonus!',
    // PWA Install
    'pwa.install.title': 'Install App?',
    'pwa.install.description': 'Add SwiftMatch to your home screen for quick access and a better experience.',
    'pwa.install.button': 'Install',
    'pwa.install.cancel': 'Later',
    'pwa.install.success': 'App installed successfully!',
    'pwa.install.dismissed': 'You can install the app later from your browser menu.',
    'pwa.install.ios_title': 'Install on iOS',
    'pwa.install.ios_description': 'To install SwiftMatch on your iPhone, tap the "Share" icon and then "Add to Home Screen".',

    // Groups
    'groups.tabs.find': 'Popular',
    'groups.tabs.top': 'Top of the Week',
    'groups.tabs.my': 'My Groups',
    'groups.create_button': 'Create Group',
    'groups.not_found': 'No groups found.',
    'groups.no_top_groups': 'There are no top groups this week.',
    'groups.not_joined': 'You have not joined any groups.',
    'groups.create.title': 'Create a new group',
    'groups.create.description': 'Fill in the information below to create a new community.',
    'groups.create.name_label': 'Group Name',
    'groups.create.name_placeholder': 'E.g., Book Lovers Club',
    'groups.create.desc_label': 'Description',
    'groups.create.desc_placeholder': 'Tell us what your group is about.',
    'groups.create.category_label': 'Category',
    'groups.create.category_placeholder': 'Select a category',
    'groups.create.submit': 'Create Group',
    'groups.create.error_title': 'Error',
    'groups.create.error_desc': 'Group name and category are required.',
    'groups.create.forbidden_title': 'Forbidden Words',
    'groups.create.forbidden_desc': 'The name or description contains forbidden words.',
    'groups.create.success_title': 'Group Created!',
    'groups.create.success_desc_start': 'Your group "',
    'groups.create.success_desc_end': '" has been successfully created.',
  }
};

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('RU');

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_lang', lang);
  };

  useEffect(() => {
    const savedLang = localStorage.getItem('app_lang') as Language;
    if (savedLang) setLanguageState(savedLang);
  }, []);

  const t = (key: string) => {
    return translations[language][key as keyof typeof translations['RU']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
